### PR TITLE
Ignore various options used by Mailpile

### PR DESCRIPTION
**Pull request by DemiMarie**
Fixes QubesOS/qubes-issues#3485

### CODE REVIEW

**Comment by DemiMarie** [comment]
PipelineRetry

**Comment by marmarek** [comment]
PipelineRetry

**Comment by marmarek** [comment]
> I think split-gpg should _unconditionally_ pass `--utf8-strings`, and reject values for `--display-charset` that are not UTF-8 or something compatible with it.

I'm not sure about forcing `--utf8-strings` (it may change the behavior if you actually use utf8 values on the command line), but rejecting UTF-8-incompatible values for `--display-charset` sounds like a good idea.

**Comment by DemiMarie** [comment]
> > I think split-gpg should _unconditionally_ pass `--utf8-strings`, and reject values for `--display-charset` that are not UTF-8 or something compatible with it.
> 
> I'm not sure about forcing `--utf8-strings` (it may change the behavior if you actually use utf8 values on the command line), but rejecting UTF-8-incompatible values for `--display-charset` sounds like a good idea.

Should `--display-charset` be ignored then?

**Comment by DemiMarie** [comment]
> > > I think split-gpg should _unconditionally_ pass `--utf8-strings`, and reject values for `--display-charset` that are not UTF-8 or something compatible with it.
> > 
> > 
> > I'm not sure about forcing `--utf8-strings` (it may change the behavior if you actually use utf8 values on the command line), but rejecting UTF-8-incompatible values for `--display-charset` sounds like a good idea.
> 
> Should `--display-charset` be ignored then?

Specifically: should it be ignored in the wrapper script, and forbidden in the C code?

**Comment by marmarek** [comment]
> Specifically: should it be ignored (if UTF-8 compatible) in the wrapper script, and forbidden in the C code?

An application may be confused if it uses `--display-charset ascii` but still get a message with some 8bit characters. So no, I don't think it should be ignored.

**Comment by DemiMarie** [comment]
> > Specifically: should it be ignored (if UTF-8 compatible) in the wrapper script, and forbidden in the C code?
> 
> An application may be confused if it uses `--display-charset ascii` but still get a message with some 8bit characters. So no, I don't think it should be ignored.

With `--display-charset ascii` GPG turns most codepoints below 256 into literal bytes and uses backslash escapes for the rest.  There is no way that I am aware of to cause all non-ASCII characters to be escaped.  The wrapper script I just push considers `--display-charset=ascii` to be an error.

**Comment by marmarek** [comment]
In practice, I don't expect any application to use anything else than UTF-8, so maybe not a huge issue. And if somebody prove us wrong, we can reconsider then.

**Review by marmarek — APPROVED** [review]

**Pull request merged**
