### PR TITLE
Tests splitgpg setup: retry if failed

### PR DESCRIPTION
**Pull request by deeplow**
Fixes QubesOS/qubes-issues#6817.

During the Thunderbird tests `setUp()` many times it fails randomly (see QubesOS/qubes-issues#6817). This retries particularly problematic setup steps when they fail. It's implemented via a decorator `retry_if_failed()`.

If other setups become problematic all one has to do is to make the setup step generally idempotent (see docstring of `retry_if_failed`) and add the decorator.

### CODE REVIEW

**Comment by deeplow** [comment]
I've done already quite some testing of this code by doing fault-injection. But before merging I'll want to do some exhaustive testing on the associated openQA VM to confirm it does solve the problem at hand.

**Comment by marmarek** [comment]
In the recent test run, set

>     * TC_10_Thunderbird_whonix-ws-15: [test_020_send_receive_inline_with_attachment](https://openqa.qubes-os.org/tests/21082#step/TC_10_Thunderbird_whonix-ws-15/3)

This failure happened in setup, and wasn't retried. But also, it seems `qubes-gpg-split-tests` package was _not_ updated in that template...

**Comment by deeplow** [comment]
Ready for final code review. But before merging, I'd like to run more extensive testing in the VM.

**Comment by deeplow** [comment]
> This failure happened in setup, and wasn't retried. But also, it seems `qubes-gpg-split-tests` package was _not_ updated in that template...

I've ran about 30 tests (including about 10 on whonix-ws). All passed except one and the one that failed was after the setup (and had not looped). I've recorded the tests and watched it in high-speed, but was unable to see any looping. So I can't confirm with the tests that this works perfectly just from looking at it runnin in the openqa VM. It's so rare we'll have to see if it happens again.

But through the fault-injection tests I did, I'm confident this mitigates the issue. Ready to merge from my side.

**Comment by marmarek** [comment]
Take a look at https://openqa.qubes-os.org/tests/21405#step/TC_10_Thunderbird_fedora-34-xfce/1
I think it should be retried? Or was it, and it didn't help?

**Comment by deeplow** [comment]
> Take a look at https://openqa.qubes-os.org/tests/21405#step/TC_10_Thunderbird_fedora-34-xfce/1
> I think it should be retried? Or was it, and it didn't help?

I believe this is a non-related bug. The retry decorator currently is only applied to do parts of the setup: [add_local_account](https://github.com/QubesOS/qubes-app-linux-split-gpg/pull/47/files#diff-9c16f54a1b3c6350b040a0c50a8522acbfa72cce6b901a11b66153d29ddf3658R189) and [configure_openpgp_account](https://github.com/QubesOS/qubes-app-linux-split-gpg/pull/47/files#diff-9c16f54a1b3c6350b040a0c50a8522acbfa72cce6b901a11b66153d29ddf3658R316) (I chose these [based on failure data](https://github.com/QubesOS/qubes-issues/issues/6817). )And here it fails even before that.

Maybe the solution for that will be applying the `retry_if_failed` decorator to another setup fuction.  But I believe that can be done as another PR.

The weird thing about that failure's stack trace is that it started in contextlib. Not in `setUp`:

```python
Traceback (most recent call last):
  File "/usr/lib64/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
AssertionError: Thunderbird setup failed: 
```

Maybe there is a `with` creating that context that I have overlooked and it all makes sense.

**Comment by marmarek** [comment]
Ah, right, this part isn't wrapped with the retry decorator. BTW exactly the same failure happened again, on the same template: https://openqa.qubes-os.org/tests/21473#step/TC_10_Thunderbird_fedora-34-xfce/1

> The weird thing about that failure's stack trace is that it started in contextlib. Not in `setUp`:

https://github.com/QubesOS/qubes-core-admin/pull/421 was not fully effective?

**Comment by deeplow** [comment]
> Ah, right, this part isn't wrapped with the retry decorator. BTW exactly the same failure happened again, on the same template: https://openqa.qubes-os.org/tests/21473#step/TC_10_Thunderbird_fedora-34-xfce/1

One more thing to the list :) Will investigate.

> > The weird thing about that failure's stack trace is that it started in contextlib. Not in `setUp`:
> 
> [QubesOS/qubes-core-admin#421](https://github.com/QubesOS/qubes-core-admin/pull/421) was not fully effective?

Check this one out: https://openqa.qubes-os.org/tests/21473#step/TC_00_Direct_debian-10/3

**Review by marmarek — APPROVED** [review]

**Pull request merged**
