### PR TITLE
Fix file descriptor handling bugs

### PR DESCRIPTION
**Pull request by DemiMarie**
See individual commit messages for details.

Fixes QubesOS/qubes-issues#7530.

### CODE REVIEW

**Comment by DemiMarie** [comment]
PipelineRetry

**Comment by DemiMarie** [comment]
PipelineRetry

**Comment by DemiMarie** [comment]
PipelineRetry

**Comment by DemiMarie** [comment]
PipelineRetry

**Comment by DemiMarie** [comment]
PipelineRetry

**Comment by DemiMarie** [comment]
PipelineRetry

**Comment by DemiMarie** [comment]
PipelineRetry

**Review by marmarek — CHANGES_REQUESTED** [review]

**Review by marmarek — APPROVED** [review]

**Pull request merged**
