### PR TITLE
Allow --export-ownertrust and --export-options backup

### PR DESCRIPTION
**Pull request by DemiMarie**
This allows exporting ownertrust values and public keyring backups, which is an essential part of migrating to split-gpg2.

Fixes QubesOS/qubes-issues#7551
Fixes QubesOS/qubes-issues#7588

### CODE REVIEW

**Comment by DemiMarie** [comment]
PipelineRetry

**Comment by DemiMarie** [comment]
PipelineRetry

**Comment by DemiMarie** [comment]
PipelineRetry

**Comment by DemiMarie** [comment]
PipelineRetry

**Comment by DemiMarie** [comment]
PipelineRetry

**Comment by marmarek** [comment]
test needs an update:
```
# test_080_option_parser
# failure: 

# timestamp 2022-07-10T13:26:16.042701
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/splitgpg/tests.py", line 375, in test_080_option_parser
    splitgpg_needs_arg = self._check_if_options_takes_argument(
  File "/usr/lib/python3.8/site-packages/splitgpg/tests.py", line 356, in _check_if_options_takes_argument
    self.fail(
AssertionError: qubes-gpg-client --export-options have not complained about --garbage options: qubes-gpg-client: Unknown export option --garbage-1
```

**Review by marmarek — APPROVED** [review]

**Pull request merged**
